/* Writes dist/index.mjs, the ESM entry, from the exports of dist/index.js: the native addon of
 * this Node.js and what index.js adds to it. build.c runs it after the build */
const fs = require('fs');
const path = require('path');

const dist = path.join(__dirname, '..', 'dist');
const uws = require(path.join(dist, 'index.js'));

const lines = [
  '// Generated by src/esm.js from the exports of index.js, do not edit',
  "import uws from './index.js';",
  '',
  'export default uws;',
  '',
  ...Object.keys(uws).map((key) => `export const ${key} = uws.${key};`),
];
fs.writeFileSync(path.join(dist, 'index.mjs'), lines.join('\n') + '\n');
