name: Build
on:
  push:
    branches: [ dockerbuild ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest",
            os: windows-latest
          }
        - {
            name: "macOS 15",
            os: macos-15
          }
        # - {
        #     name: "Ubuntu 24.04",
        #     os: ubuntu-24.04
        #   }
        - {
            name: "Ubuntu 24.04 ARM",
            os: ubuntu-24.04-arm
          }
        - {
            name: "Debian Bookworm",
            os: ubuntu-latest,
            container_image: "debian:bookworm-slim"
          }

    runs-on: ${{ matrix.config.os }}
    container:
      image: ${{ matrix.config.container_image }}
      options: --user root

    steps:
      - name: Setup Windows
        if: matrix.config.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup NASM for Windows
        if: matrix.config.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1.2.1
      - name: Setup build tools for containers
        if: matrix.config.container_image != null
        run: |
          apt-get update
          apt-get install -y build-essential git libssl-dev file zip curl jq
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26
      - name: Update binaries
        run: |
          git clone --recursive https://github.com/andygruber/uWebSockets.js.git -b dockerbuild
          cd uWebSockets.js
          ${{ matrix.config.os == 'windows-latest' && 'nmake' || 'make' }}
          ls dist
          cd tests && npm install ws && node smoke.js && cd ..
          ls dist
          git fetch origin binaries:binaries
          git checkout binaries
          cp dist/*.node .
          cp dist/*.js .
          git rev-parse master > source_commit
          ls
          ${{ matrix.config.os != 'windows-latest' && 'git checkout dockerbuild docs/index.d.ts && mv docs/index.d.ts .' || '' }}
          git status
          git config --global user.email "andreas@gruber.info"
          git config --global user.name "Andreas Gruber"
          git commit -a -m "[GitHub Actions] Updated ${{ matrix.config.os }} binaries" || true
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/andygruber/uWebSockets.js" binaries
